baseURL = 'https://example.org/'
copyright = "Huda (CC BY 4.0)"
defaultContentLanguage = "id"
title = 'Huda'
theme = "typography"

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.id]
    title = "Huda"
    languageName = "ID 🇮🇩"
    LanguageCode = "id-ID"
    contentDir = "content"
    [languages.id.params]
      madeWith = "Powered by [Hugo](https://gohugo.io/)"
[params]
  hideUntranslated = false
  favicon = "images/favicon.png"
  title = "Huda digital garden"
  description = "My digital garden website"
  images = ["images/share.webp"]
  dateFormat = "02 Jan 2006"
  generateSocialCard = true

  [params.social]
    twitter = "hudamnhd" # Twitter handle (without '@')

  [params.author]
    name = "Huda" # Your name as shown in the RSS feed metadata
    email = "muhamadhuda519@gmail,c@example.com" # Added to the footer so readers can reply to posts
