baseURL = 'https://example.org/'
copyright = "Huda (CC BY 4.0)"
defaultContentLanguage = "id"
theme = "typography"

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[related]
  threshold = 80
  includeNewer = true
  toLower = true

[[related.indices]]
  name = "tags"
  weight = 100

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.id]
    title = "Huda"
    languageName = "ID 🇮🇩"
    LanguageCode = "id-ID"
    contentDir = "content"
    [languages.id.params]
      madeWith = "Powered by [Hugo](https://gohugo.io/)"
[params]
  title = "Huda digital garden"
  description = "My digital garden website"
  hideUntranslated = false
  favicon = "images/favicon.png"
  images = ["images/share.webp"]
  dateFormat = "02 Jan 2006"
  generateSocialCard = true

  [params.social]
    twitter = "hudamnhd" # Twitter handle (without '@')

  [params.author]
    name = "Huda"
    email = "muhamadhuda519@gmail,c@example.com"
