baseURL = 'https://example.org/'
copyright = "Huda (CC BY 4.0)"
languageCode = 'id-ID'
title = 'Huda'
theme = "typography"

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.id]
    title = "Huda"
    languageName = "ID 🇮🇩"
    LanguageCode = "id-ID"
    contentDir = "content"
    [languages.id.params]
      madeWith = "Powered by [Hugo](https://gohugo.io/)"
