baseURL = 'https://example.org/'
copyright = "Huda (CC BY 4.0)"
defaultContentLanguage = "id"
theme = "typography"

[related]
  threshold = 80
  includeNewer = true
  toLower = true

[[related.indices]]
  name = "tags"
  weight = 100

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.id]
    title = "Huda"
    languageName = "ID 🇮🇩"
    LanguageCode = "id-ID"
    contentDir = "content"
    [languages.id.params]
      madeWith = "Powered by [Hugo](https://gohugo.io/)"
[params]
  title = "Huda digital garden"
  description = "My digital garden website"
  hideUntranslated = false
  favicon = "images/favicon.png"
  images = ["images/share.webp"]
  dateFormat = "02 Jan 2006"
  generateSocialCard = true

  [params.social]
    twitter = "hudamnhd" # Twitter handle (without '@')

  [params.author]
    name = "Huda"
    email = "muhamadhuda519@gmail,c@example.com"
